<!--
 * becode/javascript
 *
 * /10-asynchronous/03-handling-errors/index.html - 10.3: gestion d'erreur
 *
 * coded by leny@BeCode
 * started at 09/05/2019
-->
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <title>BeCode/JavaScript - 10.3: gestion d'erreur</title>

        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" />
        <link rel="stylesheet" href="../../_shared/css/normalize.css" />
        <link rel="stylesheet" href="../../_shared/css/styles.css" />
    </head>
    <body>
        <div class="container">
            <header>
                <h1>BeCode / JavaScript</h1>
                <h2>
                    <span>10.3</span>
                    <strong>gestion d'erreur</strong>
                </h2>
            </header>
            <div class="content">
                <section class="explain">
                    <p>La fonction <strong>window.lib.getPersons()</strong> est disponible dans le script. Elle doit recevoir un callback en paramètre. Après un petit délai, le callback sera exécuté avec deux paramètres : le premier contient une erreur (s'il y en a une, sinon <em>null</em>), le second un tableau de personnes.</p>
                    <p>Au clic sur le bouton, appelle la fonction getPersons et affiche le resultat obtenus dans la console. <strong>Attention :</strong> la fonction getPersons a plus ou moins une chance sur deux de générer une erreur. Si c'est le cas, utilise <em>console.error()</em> pour l'afficher.</p>
                </section>
                <section class="material">
                    <div class="actions">
                        <button type="button" id="run">Lancer le script</button>
                    </div>
                </section>
            </div>
        </div>

        <script src="../../_shared/lib/utils.js"></script>
        <script src="../../_shared/lib/callbacks.js"></script>
        <script src="./script.js"></script>
    </body>
</html>

